# Generated by Django 4.1.7 on 2023-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycampus',
            name='Campus_ID',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
